"""Filesystem projection of ingested documents (agent-path navigation surface).

Regenerable from the pipeline (or from Postgres via `python -m ingestion
rebuild-workspace`); never the source of truth.
"""

import json
import re
import shutil
import unicodedata
from pathlib import Path
from typing import Any

from docling_core.types.doc import DoclingDocument

# sections are the agent's unit of reading: large enough to carry context,
# small enough not to burn the prompt budget
MIN_SECTION_CHARS = 1200
MAX_SECTION_CHARS = 7000

# A table artifact is a markdown grid, which cannot be quoted verbatim, so the
# reader resolves the page back to the citable table chunks in Postgres. Format
# and parser live side by side so producer and consumer cannot drift apart.
TABLE_PAGE = " (page {page})"
TABLE_PAGE_RE = re.compile(r"\(page (\d+)\)")


def materialize(
    doc: DoclingDocument, doc_id: str, meta: dict[str, Any], workspace_dir: Path
) -> int:
    """Write document.md, tables/ artifacts and meta.json; returns the table count.

    summary.md and the gloss (LLM-generated by rebuild-workspace, paid once)
    survive the re-ingest wipe: content changes rarely invalidate them and a
    rebuild can always refresh them explicitly.
    """
    doc_dir = workspace_dir / doc_id
    summary, gloss = None, None
    if doc_dir.exists():
        summary_path = doc_dir / "summary.md"
        if summary_path.is_file():
            summary = summary_path.read_text(encoding="utf-8")
        meta_path = doc_dir / "meta.json"
        if meta_path.is_file():
            gloss = json.loads(meta_path.read_text(encoding="utf-8")).get("gloss")
        shutil.rmtree(doc_dir)
    doc_dir.mkdir(parents=True)
    if summary is not None:
        (doc_dir / "summary.md").write_text(summary, encoding="utf-8")
    if gloss is not None:
        meta = {**meta, "gloss": gloss}

    (doc_dir / "document.md").write_text(doc.export_to_markdown(), encoding="utf-8")

    table_count = 0
    if doc.tables:
        tables_dir = doc_dir / "tables"
        tables_dir.mkdir()
        for index, table in enumerate(doc.tables, 1):
            prov = table.prov[0] if table.prov else None
            header = f"# Table {index} — {doc_id}"
            if prov is not None:
                header += TABLE_PAGE.format(page=prov.page_no)
            markdown = table.export_to_markdown(doc)
            (tables_dir / f"table-{index:02d}.md").write_text(
                f"{header}\n\n{markdown}\n", encoding="utf-8"
            )
            try:
                table.export_to_dataframe(doc).to_csv(
                    tables_dir / f"table-{index:02d}.csv", index=False
                )
            except Exception:
                pass  # CSV is best-effort; the markdown artifact is the contract
            table_count += 1

    meta = {**meta, "doc_id": doc_id, "table_count": table_count}
    (doc_dir / "meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return table_count


def rebuild_index(workspace_dir: Path) -> None:
    entries = []
    for meta_path in sorted(workspace_dir.glob("*/meta.json")):
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        pages = meta.get("page_count") or "-"
        line = (
            f"- **{meta['doc_id']}** — {meta.get('title') or meta.get('filename', '?')} "
            f"({meta.get('format', '?')}, pages: {pages}, chunks: {meta.get('chunk_count', '?')}, "
            f"tables: {meta.get('table_count', 0)})"
        )
        if meta.get("gloss"):
            line += f"\n  {meta['gloss']}"
        entries.append(line)
    workspace_dir.mkdir(parents=True, exist_ok=True)
    content = "# Document index\n\n" + "\n".join(entries) + "\n"
    (workspace_dir / "_index.md").write_text(content, encoding="utf-8")


def _slug(title: str, max_length: int = 40) -> str:
    ascii_title = unicodedata.normalize("NFKD", title).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_title.lower()).strip("-")
    return slug[:max_length].rstrip("-") or "section"


def _group_sections(chunks: list[dict[str, Any]]) -> list[list[dict[str, Any]]]:
    """Consecutive chunks, split on heading change once big enough (hard cap on size)."""
    sections: list[list[dict[str, Any]]] = []
    current: list[dict[str, Any]] = []
    size = 0
    previous_headings: tuple | None = None
    for chunk in chunks:
        headings = tuple(chunk["headings"])
        if current and (
            (headings != previous_headings and size >= MIN_SECTION_CHARS)
            or size >= MAX_SECTION_CHARS
        ):
            sections.append(current)
            current, size = [], 0
        current.append(chunk)
        size += len(chunk["text"])
        previous_headings = headings
    if current:
        sections.append(current)
    return sections


def _section_title(section: list[dict[str, Any]], doc_title: str) -> str:
    for chunk in section:
        if chunk["headings"]:
            return " › ".join(chunk["headings"])
    return doc_title


def write_sections(doc_dir: Path, doc_title: str, chunks: list[dict[str, Any]]) -> int:
    """Materialize sections/ with inline chunk markers + sections.json; returns section count.

    The markers give the agent citable chunk_ids next to the exact text they cover:
    quotes copied from a section verify against the chunk in the database.
    """
    sections_dir = doc_dir / "sections"
    if sections_dir.exists():
        shutil.rmtree(sections_dir)
    sections_dir.mkdir(parents=True)

    index_entries = []
    for number, section in enumerate(_group_sections(chunks), 1):
        title = _section_title(section, doc_title)
        filename = f"{number:02d}-{_slug(title)}.md"
        parts = [f"# {title}\n"]
        for chunk in section:
            page = f" | page: {chunk['page']}" if chunk["page"] is not None else ""
            kind = " | kind: table" if chunk["kind"] == "table" else ""
            parts.append(f"<!-- chunk: {chunk['chunk_id']}{page}{kind} -->\n{chunk['text']}")
        (sections_dir / filename).write_text("\n\n".join(parts) + "\n", encoding="utf-8")

        pages = sorted({c["page"] for c in section if c["page"] is not None})
        index_entries.append(
            {
                "file": f"sections/{filename}",
                "title": title,
                "pages": pages,
                "chunk_ids": [c["chunk_id"] for c in section],
            }
        )

    (doc_dir / "sections.json").write_text(
        json.dumps(index_entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return len(index_entries)
