---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	condense(condense)
	route(route)
	retrieve(retrieve)
	generate(generate)
	agent(agent)
	tools(tools)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> condense;
	agent -.-> finalize;
	agent -.-> retrieve;
	agent -.-> tools;
	condense --> route;
	generate --> finalize;
	retrieve --> generate;
	route -.-> agent;
	route -.-> retrieve;
	tools --> agent;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
